### ISSUE TITLE
UI - Align Quantity Split/Skipped on products page

### ISSUE THREAD

**Issue by ArturHanusek** [CodingCab/ShipTown#247]
got to picklist > swipe left and click delete pick

go to orders page and look for the order with product from picklist above

align righ side better so doesn't jump to new line

![Image](https://github.com/codingcab/ShipTown/assets/11669178/aa0cb8b5-299b-424f-8c52-98cdc545cf58)

**Comment by ArturHanusek** [comment]
@robgoodliffe I didn't take the screenshot earlier but to_ship block wasn't visible on mobile as it went pass the border to the right

**Comment by robgoodliffe** [comment]
@ArturHanusek i'm working to 350px mobile width. Is this not right?

**Comment by ArturHanusek** [comment]
> @ArturHanusek i'm working to 350px mobile width. Is this not right?

yeah, but even on this, see screenshot below

I would change to 320x550px actually, this way we restrict ourselves to even smallest phone screen, anything else will be slightly bigger really

![image](https://github.com/CodingCab/ShipTown/assets/11669178/b07c8fa2-8b74-47f9-97df-319fa6ba89dc)
