### ISSUE TITLE
Reports Template - Filtering, Sort & Pagination

### ISSUE THREAD

**Issue by ArturHanusek** [CodingCab/ShipTown#252]
https://reports-template-rebuild-issue-252-shiptowndev-codingcab.myshiptown.com/reports/inventory?per_page=50&sort=-quantity&filter%5Bquantity_between%5D=0.01,999999999

https://issue-252-shiptown-robgoodliffe.myshiptown.com/reports/inventory?per_page=50&sort=-quantity&filter%5Bquantity_between%5D=0.01,999999999

equals, between, contains

report-default.blade.php

https://demo.myshiptown.com/reports/inventory?filter[warehouse_code]=WHS

![Image](https://github.com/CodingCab/ShipTown/assets/11669178/96ec1292-8789-4ba9-a86b-2b18053759ca)

![Image](https://github.com/CodingCab/ShipTown/assets/11669178/0e900d0a-0ada-45bb-8ef4-708f7640a76d)

![Image](https://github.com/CodingCab/ShipTown/assets/11669178/6dd68d7a-53c1-4859-b71d-8efada1f2bde)

![Image](https://github.com/CodingCab/ShipTown/assets/11669178/52ac2351-b57b-4348-88b5-3054fb804583)

**Comment by ArturHanusek** [comment]
Todo:
- [ ] Fix the margin between header / report body (match the mockup give)
- [ ] Fix duplicated sort indicators (match the mockup given)
- [ ] Improve pagination styling (match the mockup given)
- [ ] Fix strange per page dropdown values (10, 25, 50, 100 only)
- [ ] Move Download All button to the body of modal, footer should be only for OK, Cancel button (click through other pages to see ie [Data Collector](https://issue-252-shiptown-robgoodliffe.myshiptown.com/data-collector/1?warehouse_code=DUB) )

**Comment by robgoodliffe** [comment]
apart from this  "Improve pagination styling (match the mockup given)", as I'm not sure which mockup you are referring to (You want the grey one?), everything on this list should be done now
