### ISSUE TITLE
Move module test to tests/Unit

### ISSUE THREAD

**Issue by ArturHanusek** [CodingCab/ShipTown#294]
- [ ] update ModulesCoverageTest to require modules test under tests/Unit/Modules instead of test/Feature/Modules
- [ ] move all module tests to new location 
- [ ] ensure required routes tests are left behind (tests/Feature should be responsible for endpoint tests only)  

https://github.com/CodingCab/ShipTownDev/blob/413dc9db00e8397730a151f8750b861550ea9934/tests/Coverage/ModulesCoverageTest.php#L21

**Comment by robgoodliffe** [comment]
not sure about last point - ensure required routes tests are left behind (tests/Feature should be responsible for endpoint tests only). Can you give me an example of what you mean. I've pushed the folder change and all tests pass. https://github.com/CodingCab/ShipTownDev/pull/new/module_test_to_tests_unit_294

let me know if there's anything else to do before I make a pull request

**Comment by ArturHanusek** [comment]
its ok actually, I thought there will be some tests for routes etc which should stay under Feature, but all tests seem to be passing so ok
