### ISSUE TITLE
Add ok / cancel buttons to Options modals

### ISSUE THREAD

**Issue by ArturHanusek** [CodingCab/ShipTown#303]
Click trough all the pages and ma sure its standarized, the pages which I spotted are Products page, Tools > Restocking, Picklist

expected style:

![Image](https://github.com/CodingCab/ShipTown/assets/11669178/c4ce62fc-847c-4f1d-bf56-09981b9739df)

**Comment by robgoodliffe** [comment]
@ArturHanusek wad having issues with npm run production, so forgot to push it. Should be sorted now
