### ISSUE TITLE
[ISSUE] Cannot click data collection name

### ISSUE THREAD

**Issue by ArturHanusek** [CodingCab/ShipTown#575]
See video below. 
Clicking the  Description should bring you to:
https://shiptown.test/reports/inventory-movements?filter%5Bwarehouse_code%5D=DUB&sort=-occurred_at,-sequence_number&filter%5Bdescription%5D=Data Collection - Mens 

Clicking the  Type should bring you to:
https://shiptown.test/reports/inventory-movements?filter%5Bwarehouse_code%5D=DUB&sort=-occurred_at,-sequence_number&filter%5Btype%5D=stocktake 

https://github.com/user-attachments/assets/f3f71406-2ba9-4617-ab38-3edbacc671b4

**Comment by rizkypujiraharja** [comment]
What are the expectations when the user clicks on the description?
